# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example1.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xample1.proto\x12\x08\x65xample1\"\x85\x07\n\x0bTypeMessage\x12\x14\n\x0c\x64ouble_field\x18\x01 \x01(\x01\x12\x13\n\x0b\x66loat_field\x18\x02 \x01(\x02\x12\x13\n\x0bint32_field\x18\x03 \x01(\x05\x12\x13\n\x0bint64_field\x18\x04 \x01(\x03\x12\x14\n\x0cuint32_field\x18\x05 \x01(\r\x12\x14\n\x0cuint64_field\x18\x06 \x01(\x04\x12\x14\n\x0csint32_field\x18\x07 \x01(\x11\x12\x14\n\x0csint64_field\x18\x08 \x01(\x12\x12\x15\n\rfixed32_field\x18\t \x01(\x07\x12\x15\n\rfixed64_field\x18\n \x01(\x06\x12\x16\n\x0esfixed32_field\x18\x0b \x01(\x0f\x12\x16\n\x0esfixed64_field\x18\x0c \x01(\x10\x12\x12\n\nbool_field\x18\r \x01(\x08\x12\x14\n\x0cstring_field\x18\x0e \x01(\t\x12\x13\n\x0b\x62ytes_field\x18\x0f \x01(\x0c\x12.\n\nenum_field\x18\x10 \x01(\x0e\x32\x1a.example1.TypeMessage.Enum\x12\x36\n\tmsg_field\x18\x11 \x01(\x0b\x32#.example1.TypeMessage.NestedMessage\x12\x1b\n\x0eoptional_field\x18\x12 \x01(\x05H\x01\x88\x01\x01\x12\x15\n\x0boneof_field\x18\x13 \x01(\x05H\x00\x12\x16\n\x0eint32_repeated\x18\x14 \x03(\x05\x12\x39\n\x0cmsg_repeated\x18\x15 \x03(\x0b\x32#.example1.TypeMessage.NestedMessage\x12\x36\n\tmap_field\x18\x16 \x03(\x0b\x32#.example1.TypeMessage.MapFieldEntry\x1a;\n\rNestedMessage\x12\x14\n\x0c\x64ouble_field\x18\x01 \x01(\x01\x12\x14\n\x0cstring_field\x18\x02 \x01(\t\x1aT\n\rMapFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.example1.TypeMessage.NestedMessage:\x02\x38\x01\"4\n\x04\x45num\x12\x10\n\x0c\x45NUM_INVALID\x10\x00\x12\x0c\n\x08\x45NUM_ONE\x10\x01\x12\x0c\n\x08\x45NUM_TWO\x10\x02\x42\x13\n\x11oneof_field_outerB\x11\n\x0f_optional_fieldJ\x04\x08\x17\x10\x18R\x0ereserved_fieldb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TYPEMESSAGE_MAPFIELDENTRY']._loaded_options = None
  _globals['_TYPEMESSAGE_MAPFIELDENTRY']._serialized_options = b'8\001'
  _globals['_TYPEMESSAGE']._serialized_start=29
  _globals['_TYPEMESSAGE']._serialized_end=930
  _globals['_TYPEMESSAGE_NESTEDMESSAGE']._serialized_start=669
  _globals['_TYPEMESSAGE_NESTEDMESSAGE']._serialized_end=728
  _globals['_TYPEMESSAGE_MAPFIELDENTRY']._serialized_start=730
  _globals['_TYPEMESSAGE_MAPFIELDENTRY']._serialized_end=814
  _globals['_TYPEMESSAGE_ENUM']._serialized_start=816
  _globals['_TYPEMESSAGE_ENUM']._serialized_end=868
# @@protoc_insertion_point(module_scope)
